---
- name: Ensure deploy user exists
  ansible.builtin.user:
    name: "{{ deploy_user_username }}"
    comment: "{{ deploy_user_comment }}"
    create_home: true
    password: "!"

- name: Get home directory of deploy user
  ansible.builtin.getent:
    database: passwd
    key: "{{ deploy_user_username }}"

- name: Set home directory var for deploy user
  ansible.builtin.set_fact:
    deploy_user_home: "{{ getent_passwd[deploy_user_username][4] }}"

- name: Ensure secure home dir permissions
  ansible.builtin.file:
    path: "{{ deploy_user_home }}"
    state: directory
    owner: "{{ deploy_user_username }}"
    group: "{{ deploy_user_username }}"
    mode: '0700'
  become: true
  become_user: root

- name: Add authorized keys for deploy user
  ansible.posix.authorized_key:
    user: "{{ deploy_user_username }}"
    state: present
    key: "{{ item }}"
  loop: "{{ deploy_user_ssh_keys_present }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Remove authorized keys for deploy user
  ansible.posix.authorized_key:
    user: "{{ deploy_user_username }}"
    state: absent
    key: "{{ item }}"
  loop: "{{ deploy_user_ssh_keys_absent }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure sudo for deploy user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ deploy_user_username }}"
    content: "{{ deploy_user_username }} ALL=(ALL) NOPASSWD:ALL"
    mode: "0440"
    validate: 'visudo -cf %s'
  become: true
  become_user: root
